---
- hosts: miltronix
  become: yes
  vars:
    app_name: JetBrains Toolbox
    app_url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.24.12080-arm64.dmg?_gl=1*1lkepde*_ga*NzE5NDkzNjUwLjE2NTcwMzcyMDM.*_ga_9J976DJZ68*MTY1NzA3MDkwNS40LjEuMTY1NzA3MTYwMS40Nw..&_ga=2.96357724.1942421317.1657037203-719493650.1657037203
    installer_type: app
    install_method: dmg
    download_file_type: dmg

  roles:
    - setup
    - installer
    - cleanup


  tasks:
    - name: debug
      debug: msg="Test!"

    - name: ping
      ping: